/* COPYRIGHT (C) 2014 Hoegh Autoliners AS. All Rights Reserved. */
'use strict';
(function(nsBooking, $) {
    // Common Booking Java Script
    var commonGlobalObj = {
        'makeIDs': [],
        'modelIDs': [],
        'flagCde': [],
        'allocArray' : [],
        'itemsMap': '',
        'isCopiedToFreighted' : 'N',
        'warningMap': '',
        'allChargeid':'',
        'allChargeTimeSt' : '',
        'subBookingIdDelete':'',
        'flagDsc': [],
        'editDiscPort' : '',
        'isCopyBookingEnabled':'',
        'isMainVoyage': false,
        'isBkdAreaEmpty': false,
        'isBkdVolEmpty': false,
        'isBkdLenEmpty': false,
        'isBkdWidEmpty': false,
        'isBkdHeiEmpty': false,
        'isBkdWeiEmpty': false,
        'fnoVoyage': false,
        'mainBookingFreightBasis': '',
        'chargeBasisOptions': [],
        'chargeTypeOptions': [],
        'currencyOptions': [],
        'cargoConsignments' : [],
        'globalPartyType': [],
        'globalPartyText': {},
        'defaultMeasType': '',
        'subBookingObj': '',
        'commentTypesToDisable': [],
        'subBookingActiveId': '',
        'exactCriteriaNumber': ['Need Exact match', 'Begins with', 'Ends with', 'Contains'],
        'cargoPopulateText': '',        
        'isDiffFreight': false,
        'entityMap': {
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#39;',
            '/': '&#x2F;'
        },
        'selectedEntity': {
            'selectedBooking': '',
            'selectedBookingMenuItem': '',
            'selectedSubBooking': '',
            'selectedSubBookingMenuItem': '',
            'timeStamp': ''
        },
        'normalGridOpts': {
            'processing': true,
            'serverSide': false,
            'bFilter': true,
            'tabIndex': -1,
            'bSort': false,
            'paging': false,
            'ordering': false,
            'info': false,
            'searching': false,
            'scrollX': '600px',
            'scrollCollapse': true
        },
        'mainBookingFlag': {
            'changedOriginDest': false,
            'routeGrid': false,
            'getPossibleVoyage': false,
            'editGetPossibleVoyage': false,
            'addGetPossibleVoyage': false,
            'initialEditLoad': false,
            'initialAddLoad': false
        },
        'globalBookingFlag': {
            'mainBookingHeaderFlag': false,
            'mainBlDetailsFlag': false,
            'printSettingFlags': false,
            'currentEditLevel': '',
            'fnGoForward': '',
            'fnGoBackWard': '',
            'isCancelEvent': '',
            'isDynamicEle': false,
            'dynamicEleType': '',
            'dynamicEleClass': '',
            'dynamicEleRowNum': ''
        },
        'allCommentOptions': '',
        'hasMakebLAccess': '',
        'defaultCurrencyCode':'',
        'bookingobj':'',
        'freightedMeasureUnit': '',
        'isBookingCreatedStatus': '',
        'mainRoutekey' : '',
        'fmainTrade' : null,
        'fmainSrcPort' : null,
        'fmaindestPort' : null,
        'fcarReAvl' : 0,
        'fpuReAvl' : 0,
        'fhhReAvl' : 0,
        'fstReAvl' : 0,
        'fmaxHeightCapacity' : -1,
        'fmaxWeightCapacity' : -1,
        'copyBookingBOL' : null,
        'makeModelElement' : '',
        'mainTrade' : '',
        'quickSubCount' : '1',
        'cpySubSelect' : false,
        'bookingDataTree' : {},
        'newBookFlag' : false,
        'blStatus' : [],
        'bolTypes' : []
        
    };
    $.extend(true, nsBooking, commonGlobalObj);
})(this.booking, jQuery);